Add on callback feature for source/filter developers
Shougo/ddc.vim pull request #62
Opened 2021-10-06 11:39 UTC by LumaKernel

## What

- `onCallback` feature to replace the usage of `ddc#refresh_candidates()` as callback.
- Internally storing the `resolve` of `Promise`s.

## Pros

- Other sources won't re-run.
- Prevent refreshing of completed items.
- No need to trick in sources.
- Can be used naturally in `async/await` context.
- Can be also used in filters.
- Can be used in manual completions.

## Cons

- ?

## Play

```toml
[[plugins]]
repo = 'LumaKernel/ddc.vim'
rev = 'oncallback'

[[plugins]]
repo = 'LumaKernel/ddc-nvim-lsp'
rev = 'oncallback'
```

```toml
[[plugins]]
repo = 'LumaKernel/ddc.vim'
rev = 'oncallback'

[[plugins]]
repo = 'LumaKernel/ddc-vim-lsp'
rev = 'oncallback'
```

2021-10-06 14:59 UTC, Shougo commented on doc/ddc.txt
> +		id: String to identify the reciever. All sources and filters
`{id}`

2021-10-06 14:59 UTC, Shougo commented on doc/ddc.txt
> +		paylaod: Aribtrary object passed as resolved. optional and
`{payload}`

2021-10-06 15:00 UTC, Shougo commented on doc/ddc.txt
> +		  defaulted to |v:null|
"The default value is |v:null|."

2021-10-06 15:01 UTC, Shougo commented
`ddc#refresh_candidates()` should be deprecated in the documentation.

2021-10-06 15:02 UTC, Shougo requested changes
Please fix for my reviews.

2021-10-07 05:55 UTC, LumaKernel commented
I abandoned timeout API and use cancellation as alternative.
Please update all if you play `oncallback` branches.

2021-10-09 07:27 UTC, merged

2021-10-09 12:33 UTC, LumaKernel commented
btw, we can use this only as clean-up on cancellation.

```js
let proc;
const items = await Promise.race([
  args.onCallback('').catch((e) => {
    if (isDdcCallbackCancelError(e)) {
      proc?.kill(); // for example
    }
    throw e;
  }),
  (async () => {
    // main proc
    return [];
  })(),
]);
return items;
```