設定再構成
Shougo/ddc.vim pull request #9
Opened 2021-07-11 07:06 UTC by octaltree

状態の扱いを設計してたら巨大プルリクになっていまいました。
採用してもらえたらドキュメントも書き直します。いかがですか。

## "設定" 再構成
* 各種設定についてソース登録, フィルタ登録, 設定を行う関数が実行される順序に左右されたくない

* グローバル設定, filetype設定, バッファローカル設定がある
  - この設定は使うソースとその順序を持つ
  - 名前に紐付けてソースの設定とフィルタの設定を持つ
  - これ以外の動的な設定は思いつかなかった

* ソースごとの設定がある
  * ddcが使う設定
    - 紐付けるフィルタについてソースがデフォルトを持つ
      - そのためにはフィルタは世界で一意な通名をもつ必要がある 衝突したらユーザが適切なnameに変える
    - ユーザがソースに紐付けるフィルタを設定できる
    - ソースがmarkのデフォルトを提供する
    - ユーザがmarkを上書きできる
  * ソースが使う設定
    - ソースが自身のパラメータを持つ
    - ユーザがソースのパラメータをいじる

* フィルタごとの設定がある
  * ddcが使う設定
  * ソースが使う設定

* 設定値をtypescript側に持つ
* Ddcが提供するデフォルト値をソースのデフォルト値で上書きする。さらにそれをユーザ指定値で上書きする
* "設定"の一番上に`Custom`を使う

以上を踏まえこの3つを実装した
1. changedイベントごとに状態を取得する
2. 現在のバッファ状態における設定を得る
3. 設定に基づいてソース, フィルタを動かす

とりあえず以下のように名前をつけた
* TextChangedのたびに変わってそうなものをContext
* ユーザが設定しないと変わらないものをCustomとそのOptionsに持つ
* ソースが持つことができる任意のパラメータでddcで型付けできないものをParams

## どうでもいいこと
* plugin/にテスト用aroundソース設定が残ってる
* echodocからやり方変わってないので問題は起こってないんだと思うですけど
autocmdもnotifyも手での編集をブロックしないはずなので
最後の結果が表示されるのは最後の編集の計算が最も遅く終わったからにすぎないはず
発火時に数値インクリメントして最大値持つ結果だけを採用みたいな形でも解決するがまあいらない
ストリームやキャンセル考えたほうが有意義
* interfaceが型に関連する型を持てないので返り値型にベースクラスを使わざるをえず結果ユーザパラメータがRecord<string, unknown>になる

よろしくおねがいします。

2021-07-11 07:48 UTC, Shougo commented on README.md
> +      \ })
`ddc#custom#patch_filetype()` の example も追加してください

2021-07-11 07:50 UTC, Shougo commented
> 紐付けるフィルタについてソースがデフォルトを持つ 

デフォルト設定は source は持ちません。
デフォルト設定を持つのは source 固有設定のみです

2021-07-11 07:51 UTC, Shougo commented
> ソースがmarkのデフォルトを提供する

提供しません。提供してはいけません。
mark (などの汎用オプション)のデフォルト値は ddc 本体が静的に決定します。
この思想は絶対に変更しません。

2021-07-11 07:52 UTC, Shougo commented
> Ddcが提供するデフォルト値をソースのデフォルト値で上書きする。さらにそれをユーザ指定値で上書きする

source のデフォルト値については容認できません。

2021-07-11 07:56 UTC, Shougo commented on denops/ddc/filters/matcher_head.ts
> +  name = "matcher_head";
filter側でname をセットしないでください。

2021-07-11 07:57 UTC, Shougo commented on denops/ddc/sources/around.ts
> +  name = "around";
name をセットしてはいけません。

2021-07-11 08:00 UTC, Shougo commented on denops/ddc/sources/around.ts
> +  maxSize: number;
source 固有 parameter maxSize ですが、他の汎用パラメータと区別できるようにしたほうがよいと思っています。

2021-07-11 08:02 UTC, Shougo commented
このプルリクエストは巨大なので、テストが追加されないとマージすることはできません。

2021-07-11 08:05 UTC, Shougo commented on denops/ddc/base/source.ts
> +  options(): Partial<SourceOptions> {
オプション値を source 側で上書きできるような構造に見えます。絶対にダメです。

2021-07-11 08:06 UTC, Shougo commented on denops/ddc/base/filter.ts
> +    return {};
オプション値を filter 側で上書きできるような構造に見えます。絶対にダメです。

2021-07-11 08:08 UTC, Shougo commented
name についてですが、コンストラクタで強制的にセットするのがよいと思います。

2021-07-11 08:08 UTC, Shougo commented
> そのためにはフィルタは世界で一意な通名をもつ必要がある 衝突したらユーザが適切なnameに変える

name はユーザーが変更できないようにします。

2021-07-11 08:10 UTC, Shougo requested changes
修正が必要な箇所があります

2021-07-11 08:12 UTC, Shougo commented
> 状態の扱いを設計してたら巨大プルリクになっていまいました。
> 採用してもらえたらドキュメントも書き直します。いかがですか。

基本的なインタフェースについては悪くないと思います。
しかし、一部 ddc.vim の思想にそぐわない変更が入っているようです。
それは許容できません。

2021-07-11 08:17 UTC, Shougo commented on denops/ddc/types.ts
> +  defaultConverters: string[];
default はいりません。

2021-07-11 08:22 UTC, Shougo commented
一通り中身を確認しました。source の Options についてですが、source 側でデフォルト値をセットできる構造にしてはいけません。
これはユーザーが source が独自にセットしている値を気にする必要がないようにするためです。
確実にユーザーが設定した通りに動作するので、ユーザーが設定していないものを source がセットしてはいけません。
source 側で推奨の設定があるならば、それをドキュメントに書いてユーザーが自主的に設定できるようにします。

2021-07-11 08:25 UTC, Shougo commented
source がデフォルトで Options をセットすると、ユーザーのセットしたデフォルト値を上書きしますよね。
ユーザーは source が独自に値をセットしているか確認する必要があります。
これはユーザーを混乱させる挙動です。

2021-07-11 08:25 UTC, Shougo commented
mark についても各 source が一貫性のないデフォルト値をセットされると困るのです。

2021-07-11 08:33 UTC, octaltree commented
まずは思想の部分から

>Ddcが提供するデフォルト値をソースのデフォルト値で上書きする。さらにそれをユーザ指定値で上書きする
そこはユーザが最強にしてあります。
ソースが提供するデフォルト値をユーザが全設定を書き換えできます。
エンドユーザフルコントロールはそれはそうなんですけど

candidateが固有データを持っておりソースに対して処理すべきフィルタがあったとして、
これをドキュメントで提示するかデフォルト値として提示するか
ユーザが書き換え可能ならデフォルト値でも問題ないと私は思うんですけど
そこはどう考えていますか?

2021-07-11 08:35 UTC, Shougo commented
> ソースが提供するデフォルト値をユーザが全設定を書き換えできます。

この source がユーザーのデフォルト値を上書きできるというのがだめなんです。フルコントロールできていません。

2021-07-11 08:36 UTC, octaltree commented
まずは思想の部分から

>source がデフォルトで Options をセットすると、ユーザーのセットしたデフォルト値を上書きしますよね。
>ユーザーは source が独自に値をセットしているか確認する必要があります。
>これはユーザーを混乱させる挙動です。

そこはユーザが最強にしてあります。

>Ddcが提供するデフォルト値をソースのデフォルト値で上書きする。さらにそれをユーザ指定値で上書きする

ソースが提供するデフォルト値をユーザが全設定を書き換えできます。
エンドユーザフルコントロールはそれはそうなんですけど

candidateが固有データを持っておりソースに対して処理すべきフィルタがあったとして、
これをドキュメントで提示するかデフォルト値として提示するか
ユーザが書き換え可能ならデフォルト値でも問題ないと私は思うんですけど
どう考えていますか?

2021-07-11 08:39 UTC, Shougo commented
>ソースはどのフィルタでも動作するのは当たり前として
>candidateが固有データを持っておりソースに対して処理したほうが良いフィルタがあったとして、
>これをドキュメントで提示するかデフォルト値として提示するか
>ユーザが書き換え可能ならデフォルト値でも問題ないと私は思うんですけど
>どう考えていますか?

そういう場合もあると思います。それでも私はsourceデフォルト値を提供しないという思想を曲げるつもりはありません。

2021-07-11 08:40 UTC, Shougo commented
なぜかというと、いくらデフォルト値を提供していてもユーザーがカスタマイズしているなら面倒見れないんです。

2021-07-11 08:42 UTC, Shougo commented
source がデフォルト値を提供することで、もちろんユーザーの設定は減ります。
しかし、ユーザーが設定しようとしたときに手間が増えます。
ddc.vim は設定をするユーザーと設定をしないユーザーのどちらを救うのか考えないといけませんが、
私は設定をするユーザーを救う選択をしました。

2021-07-11 08:45 UTC, octaltree commented
実装的にもマージ必要な設定を減らして
運用的にもデフォルト設定がもたらす状態数を減らしておいた方がエンドユーザのため
わかりました

2021-07-11 08:46 UTC, Shougo commented
そうです。私がいろいろなプラグインを実装して出した結論です。新しくプラグインを作るときはそうしようと最初から考えていました。

2021-07-11 08:51 UTC, Shougo commented on README.md
> +      \ })
source 固有パラメータの設定方法が分からないので、それもサンプルが必要です。

2021-07-11 08:54 UTC, octaltree commented
> * 紐付けるフィルタについてソースがデフォルトを持つ
>   - そのためにはフィルタは世界で一意な通名をもつ必要がある 衝突したらユーザが適切なnameに変える

ソースデフォルト設定ないなら通名も必要なくなる

2021-07-11 08:55 UTC, Shougo commented
> ソースデフォルト設定ないなら通名も必要なくなる

通名はユーザーが source 固有で設定するためのものですね

2021-07-11 09:02 UTC, octaltree commented on denops/ddc/types.ts
> +  defaultConverters: string[];
'_'を名前空間から切り出してdefaultMatchersにしました。
ユーザが全てのソースに対して matchers: ['matcher_head'] を設定するならそれでもいいかと思いますが、
無くしたいいですか?

2021-07-11 09:04 UTC, octaltree commented
'_'を名前空間から切り出してdefaultMatchersにしました。
ユーザが全てのソースに対して matchers: ['matcher_head'] を設定するならそれでもいいかと思いますが、
全ソースに対してユーザが設定するdefaultMatcher無くしたいいですか?

2021-07-11 10:53 UTC, Shougo commented
> '_'を名前空間から切り出してdefaultMatchersにしました。

あー、この仕様はちょっと残してもらってよいですか。
なぜなら、ユーザーは matcher, sorter, filter 以外もデフォルト値を設定したい可能性があるんですよ。
以下は deoplete での例です。

```vim
call deoplete#custom#source('_', 'ignore_case', v:true)
call deoplete#custom#source('_', 'smart_case', v:true)
```

`_` を廃止することで、仕様を狭めるわけにはいきません。

2021-07-11 12:01 UTC, octaltree commented
* ソースデフォルトオプション廃止した
* ユーザ設定Customのテスト追加した
* ユーザのソースデフォルト設定'_'を追加した
  - typescriptでも_は使われない変数名でありゴミ箱なので、ベースと考えれば'_'だが全体と考えると'*'を使いたい
  - 
時間切れです。testの続き, example追加, doc編集は来週やります。

2021-07-11 12:13 UTC, Shougo commented
あとは API に `patch_` というプレフィクスがなぜ必要なのか分かりません。
なくてもよいのではないでしょうか？説明をお願いします。
どうしてもプレフィクスが必要なら `ddc#patch#global()` という形式にするならまだ分かります。

2021-07-11 12:14 UTC, Shougo commented on autoload/ddc/custom.vim
> +    \ 'ddc', 'patchGlobal', [a:dict], {-> v:null}, {-> v:null})
インデント入れてください

2021-07-11 12:14 UTC, Shougo commented on autoload/ddc/custom.vim
> +    \ 'ddc', 'patchFiletype', [a:ft, a:dict], {-> v:null}, {-> v:null})
インデント入れてください

2021-07-11 12:14 UTC, Shougo commented on autoload/ddc/custom.vim
> +    \ 'ddc', 'patchBuffer', [a:bufnr, a:dict], {-> v:null}, {-> v:null})
インデント入れてください

2021-07-11 12:17 UTC, Shougo commented
インタフェース自体はかなり良くなったと思います。あとは手元でテストしないといけません

2021-07-11 12:18 UTC, Shougo commented
> typescriptでも_は使われない変数名でありゴミ箱なので、ベースと考えれば'_'だが全体と考えると'*'を使いたい

ユーザー指定の設定では上書きされるので、ベースと考えたほうが適切かと思いますね

2021-07-11 12:45 UTC, octaltree commented
patchって名前は脳死でRESTから取ったんですけど、
get_, set_に加えてupdateのための諸操作を使い分けたい場合があるかもしれないのでprefixが残っています。

ここでupdateのための諸操作とは次のようなことを考えてます
例えばこういうスキーマに対して
```
type HOGE = Partial<{
  foo: number
  bar: number
}>

initial(): Hoge {
  return {};
}
var place: Hoge = initial();

get(): HOGE {
  return place;
}
delete() {
  place = initial();
}
// 作成
post(hoge: Hoge) {
  place = hoge;
}
// 置換
put(hoge: Hoge) {
  place = hoge;
}
// 部分置換
patch(hoge: Hoge): void {
  // sourceOptions等はキーごとに上書きしてるのでもう少し複雑
  place = {...place, ...hoge};
}
```

RESTはスキーマの配列に対する操作なのでPOST(Create)とPUT(Update)が別れていますが
ここでスキーマは辞書なのでそれほど分けなくてもいいかもしれません
今提供しているのはpatchとgetなので、設定をまっさらにする方法を提供するならputかdeleteかを追加する必要があります

でも、`ddc#patch#global()`で一本でオーバーロード頑張るならget, set関数別れてた方が好みです。

2021-07-11 13:08 UTC, Shougo commented
> 今提供しているのはpatchとgetなので、設定をまっさらにする方法を提供するならputかdeleteかを追加する必要があります

なるほど。source デフォルト設定がないから設定をまっさらにする方法を提供する必要はなさそう

> でも、ddc#patch#global()で一本でオーバーロード頑張るならget, set関数別れてた方が好みです。

ユーザーは明示的に get 使わないはずなので内部 API のような扱いになると思います。
無駄に API が長くなるのは私は好まないですね。
内部で使う API が長いのはよいけれど、ユーザーが使う API については気にします。

2021-07-11 13:17 UTC, Shougo commented
`get()` をユーザーに公開するなら今のままのインタフェースのほうがよいと思う。
ユーザーに公開しないなら `ddc#patch#global()` と `ddc#patch#_get_global()` が個人的には簡潔。

2021-07-11 13:27 UTC, octaltree commented
setはコピペしながら設定にファイルに書きますが
実行中に設定書き換えたりするなら
ddc#custom#_get_global: () => Partial<DdcOptions>
ddc#custom#_get_buffer: () => Record<BufNr, Partial<DdcOptions>>
これらは手で書いて確認する必要が出てくる気がします

get_local: (Filetype, BufNr) => Partial<DdcOptions>
認するなら現在バッファ取得しつつこういうのも欲しくなりそう

2021-07-11 13:39 UTC, Shougo commented
どこまで想定するかは非常に難しいけれど、ここは自由度の高い方を選んでおいたほうがよいかな。
今の仕様のままにしましょう。

2021-07-12 01:28 UTC, Shougo commented
型定義の interface ですが、全て type に置き換えてもらえますか。

2021-07-12 06:10 UTC, Shougo commented
あとはコンフリクトの修正とドキュメントですかね。そろそろ手元でも試そうかと思います。

2021-07-12 08:49 UTC, Shougo commented on README.md
> +      \ '_': {'matchers': ['matcher_head']}
最後に `,` を入れてくれたほうがよいと思います

2021-07-12 08:49 UTC, Shougo commented on README.md
> +      \ 'around': {'matchers': ['matcher_head'], 'mark': 'A'}
最後に `,` を入れてくれたほうがよいと思います

2021-07-12 08:49 UTC, Shougo commented on README.md
> +      \ 'around': {'maxSize': 500}
最後に `,` を入れてくれたほうがよいと思います

2021-07-12 08:52 UTC, Shougo commented
sourceOptions なんかが Camel case になっているのが非常に TypeScript な仕様なので気になります。
TypeScript 内で Camel case なのはよいですけど、Vim script では一般的ではないので Vim script -> Typescript のときに内部で変換できないでしょうか？
Django REST framework では確かこの変換を内部でやっていて扱いやすいのです。

2021-07-12 08:53 UTC, Shougo commented
mark がデフォルトでセットされないのも気になりましたが、これはユーザーが選択できたほうがよいのかもしれないので現在は保留。
他は今のところ問題なさそうです。

2021-07-12 10:25 UTC, Shougo commented
修正も確認しました。あとはここで指摘した問題以外は問題ないです。
https://github.com/Shougo/ddc.vim/pull/9#issuecomment-878095973

インタフェースが大幅に変更になるので、もうちょっと他の人にテストしてもらうことも検討しています。

2021-07-12 10:59 UTC, octaltree commented
sourceParamsのフィールド名がcamelCaseでDdcOptionsとsourceOptionsのフィールド名がsnake_caseなの許容しますか?
`sources: [source_name]`に対して`sourcesOptions: Record<source_name, SourceOptions>`が必要なのは、
DdcOptionsのフィールドとして数が限られているのでcamelCaseへの変換をしない特別扱いしてあげればいいですが、
同様のことがソース固有パラメータに言えこちらは有限でないのでsourceParamsのフィールドについて変換ができません。

2021-07-12 11:17 UTC, Shougo commented
>vim scriptからのddc#custom#patch_global時にSourceParams = Record<string, unknown>のフィールド名がcamelCaseでDdcOptionsとSourceOptionsのフィールド名がsnake_caseなのを許容しますか?

これはさすがに許容できないですね

> 同様のことがソース固有パラメータに言えこちらは有限でないのでsourceParamsの
> フィールドについて変換ができません。Serialize/Deserialize可能なオブジェクトと
> しか型付けできてないのが敗因です

それこそ TypeScript 内でやるのが何かの原因で厳しければ機械的な変換を Vim script
側でやってもよいと思うんですよ。
要素が無限だからやれないというのはちょっと分かりません。

2021-07-12 11:28 UTC, octaltree commented
例えば、ソースが`params.page.maxSize`フィールドにアクセスするならいいんですけど
`params.files[name]`のように辞書アクセスする場合があるので再帰的に変換をかけられないと思います。params自体がただの辞書なのでparams直下であっても辞書アクセスされる可能性があります。

2021-07-12 11:46 UTC, Shougo commented
> params自体がただの辞書なのでparams直下であっても辞書アクセスされる可能性があります。

なるほど、その懸念は理解しました。
型で縛ることができないなら source, filter の規約で Params の辞書アクセスを禁止するしかないでしょう。それならどうですか。

2021-07-12 11:47 UTC, Shougo commented
結局、camel case と snake case は TypeScript でも規約で決まっているだけで文法的に決まっているわけではない以上、
規約で縛るのでもよいはずです。

2021-07-12 11:54 UTC, octaltree commented
では、Serialize/Deserialize可能なオブジェクトにスネークケース制約ということで
オプション側は型ごとにスネークからキャメルに変換する関数を用意します

2021-07-12 12:21 UTC, Shougo commented
ちょっと今変換するべきか議論になってるので変換作業は待ってください。結論が出てからやりましょう。

2021-07-12 13:57 UTC, octaltree commented
変換書いてみましたけど保守厳しいしoptionsに限りtypescript側でもスネーク使ったほうがいいかと思います

2021-07-12 14:14 UTC, Shougo commented
> 変換書いてみましたけど保守厳しいしoptionsに限りtypescript側でもスネーク使ったほうがいいかと思います

あー、型チェックしているからですね。確かにこれだと保守が厳しいですね。
中身を機械的に変換でよいと思いましたが、sourceOptions, filterOptions が問題ですね。中身を見ないといけない。

ユーザーメリットに対して保守のデメリットが大きいですね。
変換やめて camel case に統一しましょう。

2021-07-12 14:20 UTC, Shougo commented
@octaltree 38f3342 をrevert してマージ作業を行いたいと思います。

2021-07-12 14:25 UTC, Shougo approved these changes

2021-07-12 14:26 UTC, merged

2021-07-12 14:26 UTC, Shougo commented
お疲れさまでした。マージ作業を行いました